import '../../../../core/config/purchase_config.dart';

/// Everything Help & Support reads or writes.
///
/// One file rather than five, because these are small, they change
/// together, and the category enum below is shared by three of them —
/// splitting it up would mean four files importing a fifth to name a
/// category.

/// The four help categories, plus a catch-all.
///
/// The same values are used for FAQ grouping, ticket routing, and the
/// "Report a problem" type. One enum rather than three near-identical
/// ones: a ticket about audio not playing is the same category as the FAQ
/// about audio not playing, and support filtering by it should find both.
enum HelpCategory { content, account, membership, technical, other }

extension HelpCategoryX on HelpCategory {
  /// The value stored in the database. Must match the CHECK constraint in
  /// 20260827000001_help_and_support.sql.
  String get wire => name;

  static HelpCategory fromWire(String? value) {
    return HelpCategory.values.firstWhere(
      (c) => c.name == value,
      orElse: () => HelpCategory.other,
    );
  }
}

class Faq {
  final String id;
  final HelpCategory category;
  final String question;
  final String answer;
  final String? keywords;

  /// Set by whoever wrote the article. See the migration
  /// 20260827000002_faqs_hide_on_ios.sql for why this exists.
  final bool hideOnIos;

  const Faq({
    required this.id,
    required this.category,
    required this.question,
    required this.answer,
    this.keywords,
    this.hideOnIos = false,
  });

  /// Whether this article may be shown on the current platform.
  ///
  /// Two rules, and the first is the one that matters.
  ///
  /// The whole membership category is withheld on iOS. On 27 August 2026
  /// Apple denied the External Link Account Entitlement, stating that
  /// this app does not qualify as a reader app — so Apple's own written
  /// position is that the 3.1.3(a) exemption does not apply here. An
  /// article explaining what to do when a payment made on the web has
  /// not unlocked access describes an external purchase flow, and that
  /// is exactly what a build submitted after such a letter should not
  /// put in front of a reviewer.
  ///
  /// It is a rule about the CATEGORY rather than about a row, because a
  /// row-by-row rule is one an admin writing the next membership article
  /// can forget. [hideOnIos] then covers anything else, article by
  /// article, for cases no category rule anticipates.
  ///
  /// Android is unaffected by both: it shows everything.
  bool get isAllowedOnThisPlatform {
    if (kPurchaseUiEnabled) return true; // not iOS — nothing is withheld
    return category != HelpCategory.membership && !hideOnIos;
  }

  factory Faq.fromMap(Map<String, dynamic> map) => Faq(
        id: map['id'] as String? ?? '',
        category: HelpCategoryX.fromWire(map['category'] as String?),
        question: map['question'] as String? ?? '',
        answer: map['answer'] as String? ?? '',
        keywords: map['keywords'] as String?,
        hideOnIos: map['hide_on_ios'] as bool? ?? false,
      );

  /// Whether this FAQ matches [query].
  ///
  /// Every word must appear somewhere — question, answer or keywords —
  /// rather than any word. "payment failed" should not return every FAQ
  /// containing "failed", and with a list this size an AND is what makes
  /// a two-word search narrow rather than wider.
  bool matches(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return true;
    final haystack =
        '$question $answer ${keywords ?? ''}'.toLowerCase();
    return q
        .split(RegExp(r'\s+'))
        .every((word) => haystack.contains(word));
  }
}

/// The four statuses from the PRD, named as the database stores them.
enum TicketStatus { open, inProgress, waitingOnUser, resolved }

extension TicketStatusX on TicketStatus {
  String get wire => switch (this) {
        TicketStatus.open => 'open',
        TicketStatus.inProgress => 'in_progress',
        TicketStatus.waitingOnUser => 'waiting_on_user',
        TicketStatus.resolved => 'resolved',
      };

  /// What the member reads. "Waiting for you" is phrased as an ask
  /// rather than as a state, because it is the one status that requires
  /// them to do something.
  String get label => switch (this) {
        TicketStatus.open => 'Open',
        TicketStatus.inProgress => 'In progress',
        TicketStatus.waitingOnUser => 'Waiting for you',
        TicketStatus.resolved => 'Resolved',
      };

  static TicketStatus fromWire(String? value) => switch (value) {
        'in_progress' => TicketStatus.inProgress,
        'waiting_on_user' => TicketStatus.waitingOnUser,
        'resolved' => TicketStatus.resolved,
        _ => TicketStatus.open,
      };
}

class SupportTicket {
  final String id;

  /// The short number a member can quote. Generated by the database.
  final int reference;

  final HelpCategory category;
  final String subject;
  final TicketStatus status;
  final DateTime createdAt;
  final DateTime updatedAt;

  const SupportTicket({
    required this.id,
    required this.reference,
    required this.category,
    required this.subject,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
  });

  factory SupportTicket.fromMap(Map<String, dynamic> map) => SupportTicket(
        id: map['id'] as String? ?? '',
        reference: (map['reference'] as num?)?.toInt() ?? 0,
        category: HelpCategoryX.fromWire(map['category'] as String?),
        subject: map['subject'] as String? ?? '',
        status: TicketStatusX.fromWire(map['status'] as String?),
        createdAt: DateTime.parse(map['created_at'] as String).toLocal(),
        updatedAt:
            DateTime.parse((map['updated_at'] ?? map['created_at']) as String)
                .toLocal(),
      );
}

class SupportMessage {
  final String id;
  final String body;

  /// Drives which side of the thread this sits on. Denormalised on the
  /// row so the app never has to read a staff member's profile to find
  /// out who wrote something.
  final bool fromStaff;

  final DateTime createdAt;

  const SupportMessage({
    required this.id,
    required this.body,
    required this.fromStaff,
    required this.createdAt,
  });

  factory SupportMessage.fromMap(Map<String, dynamic> map) => SupportMessage(
        id: map['id'] as String? ?? '',
        body: map['body'] as String? ?? '',
        fromStaff: map['from_staff'] as bool? ?? false,
        createdAt: DateTime.parse(map['created_at'] as String).toLocal(),
      );
}

enum FeedbackType { feature, content, general, other }

extension FeedbackTypeX on FeedbackType {
  String get wire => name;
  String get label => switch (this) {
        FeedbackType.feature => 'Suggest a feature',
        FeedbackType.content => 'Suggest content',
        FeedbackType.general => 'General feedback',
        FeedbackType.other => 'Something else',
      };
}
