-- Help & Support: tickets, the conversation on them, FAQs, and feedback.
--
-- Four tables, no new roles, no new storage bucket. `is_admin()` already
-- resolves 'admin', 'content_manager' and 'support', which is exactly the
-- staff set that should see a ticket — so support staff can work these
-- through the existing dashboard rather than through anything new.
--
-- Deliberately NOT included: an attachments table. Screenshots need a
-- storage bucket with its own policies, an upload path, and a size and
-- content-type guard, and every one of those is a place to leak one
-- member's evidence to another. It is a coherent second step, and the
-- schema below has room for it (support_messages is the natural parent).
-- Shipping tickets without it is better than shipping a bucket nobody
-- has tested.

-- ---------------------------------------------------------------------------
-- support_tickets
-- ---------------------------------------------------------------------------
create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),

  -- Short, human-quotable. "Ticket #1042" is what somebody reads out on
  -- the phone; a uuid is not. Starts high enough not to look like a
  -- brand-new system on day one.
  reference bigint generated by default as identity (start with 1001),

  user_id uuid not null references public.profiles (id) on delete cascade,

  category text not null default 'other'
    check (category in (
      'content', 'account', 'membership', 'technical', 'other'
    )),

  subject text not null,

  status text not null default 'open'
    check (status in ('open', 'in_progress', 'waiting_on_user', 'resolved')),

  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high')),

  -- Optional context, set when the member reported from a specific place.
  content_id uuid,

  -- App version, platform, OS version, device model — gathered by the app
  -- so support does not have to ask, and so a bug report arrives with the
  -- facts that make it reproducible.
  --
  -- NEVER a card number, CVV, password or auth token. Nothing in the app
  -- writes those here, and nothing should be added that does.
  client_context jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create unique index if not exists uq_support_tickets_reference
  on public.support_tickets (reference);
create index if not exists idx_support_tickets_user
  on public.support_tickets (user_id, created_at desc);
create index if not exists idx_support_tickets_status
  on public.support_tickets (status, created_at desc);

create trigger trg_support_tickets_updated_at
  before update on public.support_tickets
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- support_messages
-- ---------------------------------------------------------------------------
-- The conversation. The member's opening description is the first row
-- rather than a column on the ticket, so a reply and an opening message
-- are the same kind of thing and the thread reads in one query.
create table if not exists public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null
    references public.support_tickets (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,

  -- Denormalised so the app can render "you" versus "support" without
  -- joining profiles and without being able to read a staff member's row.
  from_staff boolean not null default false,

  body text not null,

  -- Staff-only working notes. The member must never see these, which is
  -- enforced by the column-level grant at the bottom of this file, not by
  -- politeness in the client.
  is_internal boolean not null default false,

  created_at timestamptz not null default now()
);

create index if not exists idx_support_messages_ticket
  on public.support_messages (ticket_id, created_at);

-- ---------------------------------------------------------------------------
-- faqs
-- ---------------------------------------------------------------------------
create table if not exists public.faqs (
  id uuid primary key default gen_random_uuid(),
  category text not null default 'other'
    check (category in (
      'content', 'account', 'membership', 'technical', 'other'
    )),
  question text not null,
  answer text not null,
  -- Extra words to match on that do not appear in the question. Search is
  -- done in the app over the loaded list, so this is simply more text to
  -- match, not a tsvector.
  keywords text,
  is_published boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_faqs_published
  on public.faqs (is_published, category, sort_order);

create trigger trg_faqs_updated_at
  before update on public.faqs
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- feedback
-- ---------------------------------------------------------------------------
create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  type text not null default 'general'
    check (type in ('feature', 'content', 'general', 'other')),
  message text not null,
  -- 1-5, or null when somebody wrote something without rating anything.
  rating int check (rating is null or rating between 1 and 5),
  created_at timestamptz not null default now()
);

create index if not exists idx_feedback_user
  on public.feedback (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;
alter table public.faqs enable row level security;
alter table public.feedback enable row level security;

-- Tickets: yours, or any if you are staff.
create policy "support_tickets_select_own"
  on public.support_tickets for select
  using (user_id = auth.uid() or public.is_admin());

create policy "support_tickets_insert_own"
  on public.support_tickets for insert
  with check (user_id = auth.uid());

-- Members do not update their own tickets at all. Status, priority and
-- resolution are the support team's to set, and a member who could write
-- them could mark their own ticket resolved or high-priority. There is
-- nothing else on the row they need to change — a correction is another
-- message.
create policy "support_tickets_update_staff"
  on public.support_tickets for update
  using (public.is_admin())
  with check (public.is_admin());

-- Messages: on your own ticket, and never the internal ones.
create policy "support_messages_select_own"
  on public.support_messages for select
  using (
    (not is_internal and exists (
      select 1 from public.support_tickets t
      where t.id = ticket_id and t.user_id = auth.uid()
    ))
    or public.is_admin()
  );

-- A member may only write as themselves, only on their own ticket, only
-- as a non-staff message, and never an internal note. Each of those is a
-- separate clause because each is a separate thing that would otherwise
-- be forgeable from the client.
create policy "support_messages_insert_own"
  on public.support_messages for insert
  with check (
    sender_id = auth.uid()
    and not from_staff
    and not is_internal
    and exists (
      select 1 from public.support_tickets t
      where t.id = ticket_id and t.user_id = auth.uid()
    )
  );

create policy "support_messages_insert_staff"
  on public.support_messages for insert
  with check (public.is_admin() and sender_id = auth.uid());

-- FAQs: published ones are readable by anyone, including a signed-out
-- visitor. Nothing in them is private, and help that requires a login is
-- help withheld from the person most likely to need it.
create policy "faqs_select_published"
  on public.faqs for select
  using (is_published or public.is_admin());

create policy "faqs_admin_manage"
  on public.faqs for all
  using (public.is_admin())
  with check (public.is_admin());

-- Feedback: write your own, read your own.
create policy "feedback_insert_own"
  on public.feedback for insert
  with check (user_id = auth.uid());

create policy "feedback_select_own"
  on public.feedback for select
  using (user_id = auth.uid() or public.is_admin());

-- ---------------------------------------------------------------------------
-- Column grants
-- ---------------------------------------------------------------------------
-- RLS is row-level: a policy decides WHICH rows an UPDATE may touch, never
-- WHICH COLUMNS it may set. This is the same lesson as the profiles
-- entitlement hole (F-1, 25 August) — the fix there was a column grant,
-- and the same reasoning applies here.
--
-- A member inserting a message must not be able to set `from_staff` or
-- `is_internal`. The INSERT policy above already refuses both, so this is
-- belt and braces; the grant is what makes it structural rather than
-- dependent on a WITH CHECK clause surviving a future edit.
revoke insert on public.support_messages from authenticated;
grant insert (ticket_id, sender_id, body) on public.support_messages
  to authenticated;

-- Likewise on tickets: status and priority are not the member's to set at
-- creation, and `reference` is generated.
revoke insert on public.support_tickets from authenticated;
grant insert (user_id, category, subject, content_id, client_context)
  on public.support_tickets to authenticated;

-- ---------------------------------------------------------------------------
-- Seed FAQs
-- ---------------------------------------------------------------------------
-- Written for THIS app rather than left as headings. An empty FAQ list is
-- worse than no FAQ section: it tells a member their question has been
-- anticipated and then answers nothing.
--
-- Note what these deliberately do NOT do on iOS: none of them tells
-- anybody where to buy, or what anything costs. Under App Store Guideline
-- 3.1.3(a) the iOS build is a reader app, and a help page is still part
-- of the app. Explaining that a membership exists and how to get support
-- with one is fine; pointing at a checkout is not.
insert into public.faqs (category, question, answer, keywords, sort_order)
values
  ('account',
   'How do I reset my password?',
   'On the sign-in screen, choose "Forgot password" and enter the email '
   'address you signed up with. We will send you a link to set a new one. '
   'The link is single-use and expires, so request a fresh one if it has '
   'been sitting in your inbox for a while. If the email does not arrive '
   'within a few minutes, check your spam folder before trying again — '
   'requesting several in a row can mean the older links stop working.',
   'password login signin sign in forgot reset email', 10),

  ('account',
   'I cannot sign in',
   'First check the email address, including whether it was signed up with '
   'Google rather than a password — the "Continue with Google" button and '
   'an email-and-password login are two different accounts even with the '
   'same address. If you are certain of the address, use "Forgot '
   'password" to set a new one. If that still fails, contact us and tell '
   'us the email address you are using; we can see whether an account '
   'exists for it.',
   'login signin cannot sign in locked out google', 20),

  ('account',
   'How do I delete my account?',
   'Open Settings from your profile and choose "Delete my account". This '
   'removes your account, your listening history and your downloads, and '
   'it cannot be undone. Any access you currently have is lost and is not '
   'refunded automatically — if you believe a refund is due, contact us '
   'before deleting, because once the account is gone we can no longer see '
   'its history.',
   'delete account remove close erase data', 30),

  ('content',
   'Why will an audio not play?',
   'Playback needs a connection unless the track has been downloaded. If '
   'you are online and it still will not start, close the app fully and '
   'reopen it — that re-checks your access, which is the most common '
   'cause. If it affects one track only, tell us which one; if it affects '
   'everything, tell us roughly when it started.',
   'audio not playing sound broken buffering stuck', 40),

  ('content',
   'How do I download something to listen offline?',
   'Open the track and use the download icon on the player. Downloaded '
   'audio is stored encrypted on your device and plays with no connection '
   'at all. It lives in Downloads, where you can also remove it to free '
   'space. Downloads belong to the account that made them, and are removed '
   'if that account is deleted.',
   'download offline save aeroplane airplane no internet', 50),

  ('content',
   'My downloads have disappeared',
   'Downloads are tied to the account that made them, and are cleared when '
   'access ends or when you sign out of that account. If neither applies '
   'and they have gone anyway, that is a fault and we would like to know: '
   'contact us and say roughly when you noticed, and whether it happened '
   'after reopening the app.',
   'downloads missing gone vanished disappeared lost', 60),

  ('content',
   'My progress is not saving',
   'Progress is saved as you listen and needs a connection to reach us, so '
   'a session finished offline may not be recorded until you are back '
   'online with the app open. If progress is not saving while you are '
   'plainly online, contact us.',
   'progress history continue listening resume saving', 70),

  ('membership',
   'I have paid but my access has not appeared',
   'Access is granted when the payment is confirmed, which is usually '
   'immediate but can take a few minutes. Close the app fully and reopen '
   'it — that re-checks your access. If it has been longer than that, '
   'contact us with the email address you paid with and the date, and we '
   'will find the payment and put it right.',
   'paid payment access not working unlock membership subscription', 80),

  ('membership',
   'How do I see when my access ends?',
   'Your profile shows the time remaining on your current access. If it '
   'shows nothing, either you are on the free tier or your access has no '
   'end date.',
   'membership expiry expires renew days left access', 90),

  ('membership',
   'How do I cancel, or ask for a refund?',
   'Contact us with the email address on the account and we will take care '
   'of it. Our refund terms are published in full in the Terms linked at '
   'the bottom of this screen.',
   'cancel refund stop membership money back', 100),

  ('technical',
   'The app is slow, or it crashes',
   'Close it fully and reopen it first. If it keeps happening, use "Report '
   'a problem" below rather than writing to us in general terms — it '
   'attaches your app version, device and OS automatically, and those '
   'three facts are usually what makes a crash reproducible.',
   'crash slow freeze hang bug broken lag', 110),

  ('technical',
   'I am not getting notifications',
   'Check that notifications are allowed for the app in your device '
   'settings. If they are allowed and still do not arrive, report a '
   'problem and say which kind you expected.',
   'notifications push reminders alerts silent', 120)
on conflict do nothing;
